### PR TITLE
Admin

### PR DESCRIPTION
**Pull request by awronka**

### CODE REVIEW

**Comment by awronka** [comment]
Started admin stuff. Needs more working understanding the css, but I think the admin should get a list of ten projects on init then can soft search for more specific projects as through the search bar.

**Comment by youmustfight** [comment]
Cool cool, got to admin but was unable to get a list of 10 projects. I'm going to post some redesigns soon that I think the site should go towards, which will change the functionality quite dramatically and probably the admin functionality as a result. Will keep you posted man!

**Comment by awronka** [comment]
yeah couldn't get back to the local host logged in anyway.


That being said, I'm making a personal site that i want to turn into a list of tutorials eventually.


it's at

test-site-1234.herokuapp.com

right now.


I made minesweeper with angular. fucking killed it. haha



________________________________

**Comment by nicksahler** [comment]
I hate to be a buzzkill but this is not the place for unrelated personal discussion as people are automatically subscribed to this thread.

**Pull request closed without merging**
